name: flutter_animated_cards
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.14.0+3
  flutter_staggered_grid_view: ^0.4.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  path_provider: ^2.0.1
  sqflite: ^2.0.0+3
  flutter_sidekick: ^0.1.3
  connectivity_plus: ^1.0.1
  entry: ^0.0.4
  share_plus: ^2.1.2
  clipboard: ^0.1.3
  fluttertoast: ^8.0.7
  animated_text_kit: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash:

flutter_native_splash:
  color: "#05294a"
  image: images/splash_icon.png
  android: true
  ios: true 

flutter:

  uses-material-design: true

  assets:
    - images/
  #   - images/a_dot_ham.jpeg
